### PR TITLE
[#51] Retrieve, plot, store and check all of the data for Participant 2

### PR DESCRIPTION
**Pull request by evadatinez**
- [x] retrieve dataframe

- [x] plot data

- [x] check data

----------

- [x] bug in date parsing in the function `movesDataGatheredFromWebExport`: fixed dates inconsistencies by parsing the date from the file name (see discussion below)

### CODE REVIEW

**Comment by evadatinez** [comment]
when created the dataframe for Participant2, I have an issue with the date format when we import the moves data, as show in the screenshot of the dataframe I have obtained after running my script: 
image

**Comment by oliviermirat** [comment]
@evadatinez : I've seen this kind of error before.
I think this is due to the beginning date being too late and/or the period being too short when initially creating the dataframe (not matching with the times and dates associated with the data that is being stored in the dataframe).

**Comment by evadatinez** [comment]
@oliviermirat thanks for the tip! However it does not look like this is the case in my issue: 
image

**Comment by evadatinez** [comment]
After quick inspection of the function `movesDataGatheredFromWebExport`, which is interpreting days as months and viceversa: 
image

**Comment by evadatinez** [comment]
Fun fact, the date format is different when comparing Participant 1 & 2: 
image
I would suggest to parse the date from the file name, since it is the only one where the format does not change.

**Comment by evadatinez** [comment]
fixed dates inconsistencies by parsing the date from the file name.

**Comment by evadatinez** [comment]
ready for review

**Pull request merged**
